#[test_only]
/// Tests for verify_delivery module.
///
/// Pre-sig negative tests: wrong task type, not active hunter, no task type set
/// Oracle negative tests: oracle not active, deactivated, invalid signature
/// Happy path: full verify_delivery → auto_verify_approve cycle
/// Attestation mismatch: bounty_id, hunter, item_type, quantity, target, nonce replay
///
/// Ed25519 test vectors generated by: scripts/gen_test_vectors.mjs
module bounty_escrow::test_verify_delivery;

use std::string::utf8;
use sui::test_scenario::{Self as ts};
use sui::clock;
use sui::coin;
use sui::sui::SUI;
use bounty_escrow::bounty::{Self, Bounty};
use bounty_escrow::task_type;
use bounty_escrow::constants;
use bounty_escrow::oracle;
use bounty_escrow::verify_delivery;

const CREATOR: address = @0xCA;
const HUNTER: address = @0xBB;
const VERIFIER: address = @0xDD;
const ORACLE_ADMIN: address = @0xAD;
const ORACLE_ADDR: address = @0x0A;

const NOW: u64 = 1_000_000_000;
const DEADLINE: u64 = 1_000_000_000 + 86_400_000;
const GRACE: u64 = 86_400_000;

// Dummy attestation data (will fail signature check, but tests abort before that)
const DUMMY_MSG: vector<u8> = x"00";
const DUMMY_SIG: vector<u8> = x"00";

// === Ed25519 Test Vectors (DELIVERY) ===
// Generated by: node scripts/gen_test_vectors.mjs delivery <bounty_id>
// Seed: 0x42 + 31 zero bytes
const ORACLE_PUBKEY: vector<u8> = x"ccbc3da2c4267cc8553be0c7b5790cc75a121297528462c3d2cc679d16eb8684";

// Happy path: nonce=1, item_type_id=100, quantity=10, assembly=@0x0
const DELIVERY_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000bb64000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000ca9a3b000000000100000000000000";
const DELIVERY_SIG: vector<u8> = x"89e81fc8fc9f48f1e28e0a0af94039e909517f87b2417d6169aa18943f3403ccced10252a672caf2f85ec1d85c14379198368cce176e212d45507633c567b70a";

// Wrong bounty_id
const DELIVERY_WRONG_BOUNTY_MSG: vector<u8> = x"000000000000000000000000000000000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000bb64000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000ca9a3b000000000200000000000000";
const DELIVERY_WRONG_BOUNTY_SIG: vector<u8> = x"178d6dceed8108c69eb975e5e2b31cf8d762e21a2a101ecc04fef4d94806f43e57f9451aa5739efbc6c760eb2a420d0b29a55e5aacb25baf59e951dd61735007";

// Wrong hunter
const DELIVERY_WRONG_HUNTER_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000ee64000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000ca9a3b000000000300000000000000";
const DELIVERY_WRONG_HUNTER_SIG: vector<u8> = x"b13e650bc65ea51817dcb3b88a34cd77875a08a8f285787c644d74be1b45c7efb9a4308e0ea28c84e28a0bdb0042c03a2729b77a92f6d32e327c2b5ffc47e306";

// Wrong item_type_id (999 instead of 100)
const DELIVERY_WRONG_ITEM_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000bbe7030000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000ca9a3b000000000400000000000000";
const DELIVERY_WRONG_ITEM_SIG: vector<u8> = x"e32164af8dd3e8627c179308cb16ef8f0025c0c7e0254d24d2c20a9be1450d38963854d12b0bc7d9791b324aeadce9b8b66168780c7688ba8d64612f258d1705";

// Insufficient quantity (5 < min 10)
const DELIVERY_LOW_QTY_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000bb64000000000000000500000000000000000000000000000000000000000000000000000000000000000000000000000000ca9a3b000000000500000000000000";
const DELIVERY_LOW_QTY_SIG: vector<u8> = x"698ed53342aadebd12a7d3e49f393c3a0491d1ca71d56a01f1fffeaecb95e80a98a12e3bd3d773062866b73eb7c32cefd91fa20801c3176710a4520dbd9fb50c";

// Nonce replay (nonce=1 again, different timestamp)
const DELIVERY_REPLAY_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000bb64000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000943577000000000100000000000000";
const DELIVERY_REPLAY_SIG: vector<u8> = x"e668112f5891986c21429ce8f32af0b0f49c7ab20828532ee78086a085b2cea53e8761ccca4b317b78284768aaaf10b491d9aafc431eeada2aeaedd74e48d50f";

// Target assembly mismatch (attestation=@0xBB, criteria=@0xAA)
const DELIVERY_WRONG_TARGET_MSG: vector<u8> = x"90c5264c9da2b340fdc9fbd15ad3f0a181a57afa7ae55b15a3c5dce6b31f45c800000000000000000000000000000000000000000000000000000000000000bb64000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000bb00ca9a3b000000000600000000000000";
const DELIVERY_WRONG_TARGET_SIG: vector<u8> = x"38a1c6b87150a1b26c24504eeae8905b0422162f4d93d996611d1194d9edc394483b2e34b9aa58edb37c1d92c1616564f5d589a729db31236d4c1eeb0c432f04";

// =====================================================================
// Setup helpers
// =====================================================================

fun setup_bounty(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, CREATOR);
    let coin = coin::mint_for_testing<SUI>(5000, ts::ctx(scenario));
    bounty::create<SUI>(
        utf8(b"Deliver items"), utf8(b"desc"), coin,
        1000, 100, 5, DEADLINE, GRACE, 100,
        VERIFIER, clock, ts::ctx(scenario),
    );
}

fun setup_delivery_task(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, CREATOR);
    let mut bounty = ts::take_shared<Bounty<SUI>>(scenario);
    task_type::set_task_type(&mut bounty, constants::task_type_delivery(), clock, ts::ctx(scenario));
    task_type::set_delivery_criteria(&mut bounty, 100, 10, @0x0, ts::ctx(scenario));
    ts::return_shared(bounty);
}

fun setup_oracle_registry(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, ORACLE_ADMIN);
    let registry = oracle::create_registry(clock, ts::ctx(scenario));
    oracle::share_registry_for_testing(registry);
}

fun hunter_claim(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(scenario);
    let stake = coin::mint_for_testing<SUI>(100, ts::ctx(scenario));
    bounty::claim(&mut bounty, stake, clock, ts::ctx(scenario));
    ts::return_shared(bounty);
}

fun register_oracle_with_pubkey(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, ORACLE_ADMIN);
    let mut registry = ts::take_shared<oracle::OracleRegistry>(scenario);
    oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), ORACLE_PUBKEY, clock, ts::ctx(scenario));
    ts::return_shared(registry);
}

/// Full happy-path setup: bounty + delivery task + hunter claim + oracle registry + oracle registered.
fun full_delivery_setup(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    setup_bounty(scenario, clock);
    setup_delivery_task(scenario, clock);
    hunter_claim(scenario, clock);
    setup_oracle_registry(scenario, clock);
    register_oracle_with_pubkey(scenario, clock);
}

/// Same as full_delivery_setup but with specific target_assembly in criteria.
fun full_delivery_setup_with_target(scenario: &mut ts::Scenario, clock: &clock::Clock, target: address) {
    setup_bounty(scenario, clock);
    // Custom delivery task with specific target
    ts::next_tx(scenario, CREATOR);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(scenario);
        task_type::set_task_type(&mut bounty, constants::task_type_delivery(), clock, ts::ctx(scenario));
        task_type::set_delivery_criteria(&mut bounty, 100, 10, target, ts::ctx(scenario));
        ts::return_shared(bounty);
    };
    hunter_claim(scenario, clock);
    setup_oracle_registry(scenario, clock);
    register_oracle_with_pubkey(scenario, clock);
}

// =====================================================================
// Negative: wrong task type (KILL instead of DELIVERY)
// =====================================================================

#[test, expected_failure(abort_code = 65)] // e_wrong_task_type
fun test_verify_delivery_wrong_task_type() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);

    // Set KILL instead of DELIVERY
    ts::next_tx(&mut scenario, CREATOR);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        task_type::set_task_type(&mut bounty, constants::task_type_kill(), &clock, ts::ctx(&mut scenario));
        task_type::set_kill_criteria(&mut bounty, 0, 0, 1, ts::ctx(&mut scenario));
        ts::return_shared(bounty);
    };
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: no task type set (defaults to CUSTOM)
// =====================================================================

#[test, expected_failure(abort_code = 65)] // e_wrong_task_type
fun test_verify_delivery_no_task_type() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);
    // No set_task_type
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: hunter not active (not claimed)
// =====================================================================

#[test, expected_failure(abort_code = 17)] // e_hunter_not_active
fun test_verify_delivery_hunter_not_active() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);
    setup_delivery_task(&mut scenario, &clock);
    // Hunter does NOT claim
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: oracle not active (not registered)
// =====================================================================

#[test, expected_failure(abort_code = 75)] // e_oracle_not_active
fun test_verify_delivery_oracle_not_active() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);
    setup_delivery_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    // Oracle NOT registered → verify_attestation aborts with e_oracle_not_active

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: oracle deactivated
// =====================================================================

#[test, expected_failure(abort_code = 75)] // e_oracle_not_active
fun test_verify_delivery_oracle_deactivated() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);
    setup_delivery_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    // Register then deactivate oracle
    ts::next_tx(&mut scenario, ORACLE_ADMIN);
    {
        let mut registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        // 32-byte dummy pubkey
        let pubkey = x"0000000000000000000000000000000000000000000000000000000000000001";
        oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), pubkey, &clock, ts::ctx(&mut scenario));
        oracle::deactivate_oracle(&mut registry, ORACLE_ADDR, ts::ctx(&mut scenario));
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: invalid attestation signature (registered oracle, bad sig)
// =====================================================================

#[test, expected_failure(abort_code = 77)] // e_invalid_attestation
fun test_verify_delivery_invalid_signature() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_bounty(&mut scenario, &clock);
    setup_delivery_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    // Register oracle with real-looking 32-byte pubkey
    ts::next_tx(&mut scenario, ORACLE_ADMIN);
    {
        let mut registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        let pubkey = x"d75a980182b10ab7d54bfed3c964073a0ee172f3daa3f4a18446b7c8b7b9f1cc";
        oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), pubkey, &clock, ts::ctx(&mut scenario));
        ts::return_shared(registry);
    };

    // Bad signature (wrong length/content) → ed25519 verify fails
    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    let bad_sig = x"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DUMMY_MSG, bad_sig, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// HAPPY PATH: verify_delivery → auto_verify_approve
// =====================================================================

#[test]
fun test_verify_delivery_happy_path() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    // No abort = verify_delivery succeeded + hunter auto-approved
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        verify_delivery::verify_delivery(
            &mut bounty, &registry, DELIVERY_MSG, DELIVERY_SIG, ORACLE_ADDR,
            &clock, ts::ctx(&mut scenario),
        );
        ts::return_shared(bounty);
        ts::return_shared(registry);
    };

    // Claim reward — proves hunter was truly approved
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let ticket = ts::take_from_sender<bounty::ClaimTicket>(&scenario);
        bounty::claim_reward(&mut bounty, ticket, ts::ctx(&mut scenario));
        assert!(bounty::completed_claims(&bounty) == 1);
        ts::return_shared(bounty);
    };

    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: attestation bounty_id mismatch
// =====================================================================

#[test, expected_failure(abort_code = 79)] // e_attestation_bounty_mismatch
fun test_verify_delivery_bounty_id_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_WRONG_BOUNTY_MSG, DELIVERY_WRONG_BOUNTY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: attestation hunter mismatch
// =====================================================================

#[test, expected_failure(abort_code = 80)] // e_attestation_hunter_mismatch
fun test_verify_delivery_hunter_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_WRONG_HUNTER_MSG, DELIVERY_WRONG_HUNTER_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: item_type_id mismatch
// =====================================================================

#[test, expected_failure(abort_code = 89)] // e_delivery_item_mismatch
fun test_verify_delivery_item_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_WRONG_ITEM_MSG, DELIVERY_WRONG_ITEM_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: quantity insufficient (5 < min 10)
// =====================================================================

#[test, expected_failure(abort_code = 88)] // e_delivery_quantity_insufficient
fun test_verify_delivery_quantity_insufficient() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_LOW_QTY_MSG, DELIVERY_LOW_QTY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: target assembly mismatch (criteria=@0xAA, attestation=@0xBB)
// =====================================================================

#[test, expected_failure(abort_code = 90)] // e_delivery_target_mismatch
fun test_verify_delivery_target_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    // Setup with specific target @0xAA — attestation has @0xBB
    full_delivery_setup_with_target(&mut scenario, &clock, @0xAA);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_WRONG_TARGET_MSG, DELIVERY_WRONG_TARGET_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: nonce replay (use nonce=1 twice)
// =====================================================================

#[test, expected_failure(abort_code = 78)] // e_nonce_already_used
fun test_verify_delivery_nonce_replay() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    full_delivery_setup(&mut scenario, &clock);

    // First verify — succeeds, uses nonce=1
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        verify_delivery::verify_delivery(
            &mut bounty, &registry, DELIVERY_MSG, DELIVERY_SIG, ORACLE_ADDR,
            &clock, ts::ctx(&mut scenario),
        );
        ts::return_shared(bounty);
        ts::return_shared(registry);
    };

    // Second verify — same nonce=1, different timestamp → replay abort
    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
    verify_delivery::verify_delivery(
        &mut bounty, &registry, DELIVERY_REPLAY_MSG, DELIVERY_REPLAY_SIG, ORACLE_ADDR,
        &clock, ts::ctx(&mut scenario),
    );
    ts::return_shared(bounty);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}
