#[test_only]
/// Tests for verify_build module.
///
/// Pre-sig negative tests: wrong task type, not active hunter, character mismatch
/// Oracle negative tests: oracle not active, deactivated, invalid signature
/// Happy path: full verify_build → auto_verify_approve → claim_reward
/// Attestation mismatch: bounty_id, hunter, assembly_id, type_id, solar_system, nonce replay
///
/// Ed25519 test vectors generated by: scripts/gen_test_vectors.mjs
module bounty_escrow::test_verify_build;

use std::string::utf8;
use sui::test_scenario::{Self as ts};
use sui::clock;
use sui::coin;
use sui::sui::SUI;
use world::access::AdminACL;
use world::assembly::{Self, Assembly};
use world::character::{Self, Character};
use world::network_node::{Self, NetworkNode};
use world::object_registry::ObjectRegistry;
use world::test_helpers::{Self, admin, tenant};
use bounty_escrow::bounty::{Self, Bounty};
use bounty_escrow::task_type;
use bounty_escrow::constants;
use bounty_escrow::oracle;
use bounty_escrow::verify_build;

const CREATOR: address = @0xCA;
const HUNTER: address = @0xBB;
const VERIFIER: address = @0xDD;
const ORACLE_ADMIN: address = @0xAD;
const ORACLE_ADDR: address = @0x0A;

const HUNTER_GAME_ID: u32 = 5001;
const ASSEMBLY_ITEM_ID: u64 = 1001;
const ASSEMBLY_TYPE_ID: u64 = 8888;
const NWN_ITEM_ID: u64 = 5000;
const NWN_TYPE_ID: u64 = 111000;
const LOCATION_HASH: vector<u8> = x"7a8f3b2e9c4d1a6f5e8b2d9c3f7a1e5b7a8f3b2e9c4d1a6f5e8b2d9c3f7a1e5b";

const NOW: u64 = 1_000_000_000;
const DEADLINE: u64 = 1_000_000_000 + 86_400_000;
const GRACE: u64 = 86_400_000;

const DUMMY_MSG: vector<u8> = x"00";
const DUMMY_SIG: vector<u8> = x"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

// === Ed25519 Test Vectors (BUILD) ===
// Generated by: node scripts/gen_test_vectors.mjs build <bounty_id> <assembly_id>
// Seed: 0x42 + 31 zero bytes
const ORACLE_PUBKEY: vector<u8> = x"ccbc3da2c4267cc8553be0c7b5790cc75a121297528462c3d2cc679d16eb8684";

// Happy path: nonce=1, assembly_type_id=8888, solar=0
const BUILD_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000bbb82200000000000000000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300ca9a3b000000000100000000000000";
const BUILD_SIG: vector<u8> = x"48bf9519d1b11d3d437a0247993f8514843385181114853a17a558327b15e968aad162379d58bca085c832e13506bf905a4afce9440e9f8bf461eec70ef19906";

// Wrong bounty_id
const BUILD_WRONG_BOUNTY_MSG: vector<u8> = x"000000000000000000000000000000000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000bbb82200000000000000000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300ca9a3b000000000200000000000000";
const BUILD_WRONG_BOUNTY_SIG: vector<u8> = x"80b73c9123593c4dd5a5c92b10b9d46ce01aa8d468d233541249588de46ad0748c3b054e2a80f0c3737ce9306ec1f7cec35aa1299185dbe4c92dd5fe2fa20309";

// Wrong hunter
const BUILD_WRONG_HUNTER_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000eeb82200000000000000000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300ca9a3b000000000300000000000000";
const BUILD_WRONG_HUNTER_SIG: vector<u8> = x"1f7e8742c5b9eb17dcc452292e158af6e29580c0f6382b4cf41f818b92e57c10bcb2e26d1b5780df6892c99193d97ed45987588595bbde71a52c20c57718300c";

// Wrong assembly_id
const BUILD_WRONG_ASSEMBLY_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000bbb8220000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dead00ca9a3b000000000400000000000000";
const BUILD_WRONG_ASSEMBLY_SIG: vector<u8> = x"7e2a5fa1e2f40e479e81b7a6119f6ecaea82c718736371ad29639d8259d864c593af9fb1e4dec333ad2e1d64e2eda998b0cb964864ef8768bfb036210e52dc0b";

// Wrong assembly_type_id (9999 instead of 8888)
const BUILD_WRONG_TYPE_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000bb0f2700000000000000000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300ca9a3b000000000500000000000000";
const BUILD_WRONG_TYPE_SIG: vector<u8> = x"53937be7ca867f20b5f3cc5123610cb6fb7fc06f64d9ab0dec3a24f84a91d2a0cd367004cce2b2dd4675ab325decb8381986f3880f29707c9d368b2b224e830d";

// Solar system mismatch (att=99, criteria=42)
const BUILD_WRONG_SOLAR_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000bbb82200000000000063000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300ca9a3b000000000600000000000000";
const BUILD_WRONG_SOLAR_SIG: vector<u8> = x"eeeca611e89e73105186d7e5036b2e4d641d9bdd6274754f894da16e2ddafd3478f74b61a093da4684fd435ebd9241ce5488d0ef2c49d037bfd260acd217e40d";

// Nonce replay (nonce=1 again, different timestamp)
const BUILD_REPLAY_MSG: vector<u8> = x"fa873fa06e5ffa6a3f2273b8a3eeb68f2c1c10734a60f93046dbea2d9af5c6b100000000000000000000000000000000000000000000000000000000000000bbb82200000000000000000000000000002ac43254250ebb3084798c5f30a989f8c1228cc2a7e57f5af03aeac20e10ac7300943577000000000100000000000000";
const BUILD_REPLAY_SIG: vector<u8> = x"1fbe33589af9cdc24e433591ac3146e87e1afb06e7ab09515796709ce690e5438fb726e3f97437f1e5a473eef00fb41d027a5cad5e5d99e065ede0eff271c30e";

// =====================================================================
// Setup helpers
// =====================================================================

/// Full world setup + fuel + energy config.
fun setup_world_full(scenario: &mut ts::Scenario) {
    test_helpers::setup_world(scenario);
    test_helpers::configure_fuel(scenario);
    test_helpers::configure_assembly_energy(scenario);
}

fun setup_character(scenario: &mut ts::Scenario, owner: address, game_id: u32): ID {
    ts::next_tx(scenario, admin());
    let mut registry = ts::take_shared<ObjectRegistry>(scenario);
    let admin_acl = ts::take_shared<AdminACL>(scenario);
    let character = character::create_character(
        &mut registry, &admin_acl,
        game_id, tenant(), 100, owner, utf8(b"hunter"), ts::ctx(scenario),
    );
    let id = object::id(&character);
    character::share_character(character, &admin_acl, ts::ctx(scenario));
    ts::return_shared(registry);
    ts::return_shared(admin_acl);
    id
}

fun setup_network_node(scenario: &mut ts::Scenario, char_id: ID): ID {
    ts::next_tx(scenario, admin());
    let mut registry = ts::take_shared<ObjectRegistry>(scenario);
    let character = ts::take_shared_by_id<Character>(scenario, char_id);
    let admin_acl = ts::take_shared<AdminACL>(scenario);
    let nwn = network_node::anchor(
        &mut registry, &character, &admin_acl,
        NWN_ITEM_ID, NWN_TYPE_ID, LOCATION_HASH,
        1000, 3_600_000, 100, ts::ctx(scenario),
    );
    let id = object::id(&nwn);
    nwn.share_network_node(&admin_acl, ts::ctx(scenario));
    ts::return_shared(character);
    ts::return_shared(admin_acl);
    ts::return_shared(registry);
    id
}

fun setup_assembly(scenario: &mut ts::Scenario, nwn_id: ID, char_id: ID): ID {
    ts::next_tx(scenario, admin());
    let character = ts::take_shared_by_id<Character>(scenario, char_id);
    let mut registry = ts::take_shared<ObjectRegistry>(scenario);
    let mut nwn = ts::take_shared_by_id<NetworkNode>(scenario, nwn_id);
    let admin_acl = ts::take_shared<AdminACL>(scenario);
    let assembly = assembly::anchor(
        &mut registry, &mut nwn, &character, &admin_acl,
        ASSEMBLY_ITEM_ID, ASSEMBLY_TYPE_ID, LOCATION_HASH, ts::ctx(scenario),
    );
    let id = object::id(&assembly);
    assembly.share_assembly(&admin_acl, ts::ctx(scenario));
    ts::return_shared(character);
    ts::return_shared(admin_acl);
    ts::return_shared(registry);
    ts::return_shared(nwn);
    id
}

fun setup_bounty(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, CREATOR);
    let coin = coin::mint_for_testing<SUI>(5000, ts::ctx(scenario));
    bounty::create<SUI>(
        utf8(b"Build assembly"), utf8(b"desc"), coin,
        1000, 100, 5, DEADLINE, GRACE, 100,
        VERIFIER, clock, ts::ctx(scenario),
    );
}

fun setup_build_task(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, CREATOR);
    let mut bounty = ts::take_shared<Bounty<SUI>>(scenario);
    task_type::set_task_type(&mut bounty, constants::task_type_build(), clock, ts::ctx(scenario));
    task_type::set_build_criteria(&mut bounty, ASSEMBLY_TYPE_ID, 0, ts::ctx(scenario));
    ts::return_shared(bounty);
}

fun setup_oracle_registry(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, ORACLE_ADMIN);
    let registry = oracle::create_registry(clock, ts::ctx(scenario));
    oracle::share_registry_for_testing(registry);
}

fun hunter_claim(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(scenario);
    let stake = coin::mint_for_testing<SUI>(100, ts::ctx(scenario));
    bounty::claim(&mut bounty, stake, clock, ts::ctx(scenario));
    ts::return_shared(bounty);
}

fun register_oracle_with_pubkey(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    ts::next_tx(scenario, ORACLE_ADMIN);
    let mut registry = ts::take_shared<oracle::OracleRegistry>(scenario);
    oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), ORACLE_PUBKEY, clock, ts::ctx(scenario));
    ts::return_shared(registry);
}

/// Full world + assembly setup. Returns (char_id, assembly_id).
fun full_world_setup(scenario: &mut ts::Scenario, clock: &mut clock::Clock): (ID, ID) {
    clock::set_for_testing(clock, NOW);
    setup_world_full(scenario);
    let char_id = setup_character(scenario, HUNTER, HUNTER_GAME_ID);
    let nwn_id = setup_network_node(scenario, char_id);
    let assembly_id = setup_assembly(scenario, nwn_id, char_id);
    (char_id, assembly_id)
}

// =====================================================================
// Negative: wrong task type (KILL instead of BUILD)
// =====================================================================

#[test, expected_failure(abort_code = 65)] // e_wrong_task_type
fun test_verify_build_wrong_task_type() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);

    // Set KILL instead of BUILD
    ts::next_tx(&mut scenario, CREATOR);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        task_type::set_task_type(&mut bounty, constants::task_type_kill(), &clock, ts::ctx(&mut scenario));
        task_type::set_kill_criteria(&mut bounty, 0, 0, 1, ts::ctx(&mut scenario));
        ts::return_shared(bounty);
    };
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: no task type set (defaults to CUSTOM)
// =====================================================================

#[test, expected_failure(abort_code = 65)] // e_wrong_task_type
fun test_verify_build_no_task_type() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    // No set_task_type
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: hunter not active (not claimed)
// =====================================================================

#[test, expected_failure(abort_code = 17)] // e_hunter_not_active
fun test_verify_build_hunter_not_active() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    // Hunter does NOT claim
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: character mismatch (character.address != sender)
// =====================================================================

#[test, expected_failure(abort_code = 73)] // e_character_mismatch
fun test_verify_build_character_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clock, NOW);
    setup_world_full(&mut scenario);
    // Character owned by @0xEE, not HUNTER
    let char_id = setup_character(&mut scenario, @0xEE, HUNTER_GAME_ID);
    let nwn_id = setup_network_node(&mut scenario, char_id);
    let assembly_id = setup_assembly(&mut scenario, nwn_id, char_id);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: oracle not active (not registered)
// =====================================================================

#[test, expected_failure(abort_code = 75)] // e_oracle_not_active
fun test_verify_build_oracle_not_active() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    // Oracle NOT registered

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: oracle deactivated
// =====================================================================

#[test, expected_failure(abort_code = 75)] // e_oracle_not_active
fun test_verify_build_oracle_deactivated() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    // Register then deactivate oracle
    ts::next_tx(&mut scenario, ORACLE_ADMIN);
    {
        let mut registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        let pubkey = x"d75a980182b10ab7d54bfed3c964073a0ee172f3daa3f4a18446b7c8b7b9f1cc";
        oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), pubkey, &clock, ts::ctx(&mut scenario));
        oracle::deactivate_oracle(&mut registry, ORACLE_ADDR, ts::ctx(&mut scenario));
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: invalid attestation signature
// =====================================================================

#[test, expected_failure(abort_code = 77)] // e_invalid_attestation
fun test_verify_build_invalid_signature() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);

    // Register oracle with real pubkey
    ts::next_tx(&mut scenario, ORACLE_ADMIN);
    {
        let mut registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        let pubkey = x"d75a980182b10ab7d54bfed3c964073a0ee172f3daa3f4a18446b7c8b7b9f1cc";
        oracle::register_oracle(&mut registry, ORACLE_ADDR, utf8(b"oracle"), pubkey, &clock, ts::ctx(&mut scenario));
        ts::return_shared(registry);
    };

    // Bad signature → ed25519 verify fails
    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        DUMMY_MSG, DUMMY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// HAPPY PATH: verify_build → auto_verify_approve → claim_reward
// =====================================================================

#[test]
fun test_verify_build_happy_path() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    // Verify build — no abort = success + auto-approved
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
        let character = ts::take_shared_by_id<Character>(&scenario, char_id);
        let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        verify_build::verify_build(
            &mut bounty, &assembly, &character, &registry,
            BUILD_MSG, BUILD_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
        );
        ts::return_shared(bounty);
        ts::return_shared(assembly);
        ts::return_shared(character);
        ts::return_shared(registry);
    };

    // Claim reward — proves hunter was truly approved
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let ticket = ts::take_from_sender<bounty::ClaimTicket>(&scenario);
        bounty::claim_reward(&mut bounty, ticket, ts::ctx(&mut scenario));
        assert!(bounty::completed_claims(&bounty) == 1);
        ts::return_shared(bounty);
    };

    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: attestation bounty_id mismatch
// =====================================================================

#[test, expected_failure(abort_code = 79)] // e_attestation_bounty_mismatch
fun test_verify_build_bounty_id_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_WRONG_BOUNTY_MSG, BUILD_WRONG_BOUNTY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: attestation hunter mismatch
// =====================================================================

#[test, expected_failure(abort_code = 80)] // e_attestation_hunter_mismatch
fun test_verify_build_hunter_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_WRONG_HUNTER_MSG, BUILD_WRONG_HUNTER_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: assembly_id mismatch (attestation has wrong assembly)
// =====================================================================

#[test, expected_failure(abort_code = 87)] // e_not_assembly_owner
fun test_verify_build_assembly_id_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_WRONG_ASSEMBLY_MSG, BUILD_WRONG_ASSEMBLY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: assembly_type_id mismatch (9999 instead of 8888)
// =====================================================================

#[test, expected_failure(abort_code = 87)] // e_not_assembly_owner (reused for type mismatch)
fun test_verify_build_type_id_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_WRONG_TYPE_MSG, BUILD_WRONG_TYPE_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: solar system mismatch (att=99, criteria=42)
// =====================================================================

#[test, expected_failure(abort_code = 70)] // e_solar_system_mismatch
fun test_verify_build_solar_mismatch() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);

    // Set build criteria with specific solar_system=42
    ts::next_tx(&mut scenario, CREATOR);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        task_type::set_task_type(&mut bounty, constants::task_type_build(), &clock, ts::ctx(&mut scenario));
        task_type::set_build_criteria(&mut bounty, ASSEMBLY_TYPE_ID, 42, ts::ctx(&mut scenario));
        ts::return_shared(bounty);
    };
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    // Attestation has solar=99, criteria expects solar=42
    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_WRONG_SOLAR_MSG, BUILD_WRONG_SOLAR_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// =====================================================================
// Negative: nonce replay (use nonce=1 twice)
// =====================================================================

#[test, expected_failure(abort_code = 78)] // e_nonce_already_used
fun test_verify_build_nonce_replay() {
    let mut scenario = ts::begin(CREATOR);
    let mut clock = clock::create_for_testing(ts::ctx(&mut scenario));
    let (char_id, assembly_id) = full_world_setup(&mut scenario, &mut clock);
    setup_bounty(&mut scenario, &clock);
    setup_build_task(&mut scenario, &clock);
    hunter_claim(&mut scenario, &clock);
    setup_oracle_registry(&mut scenario, &clock);
    register_oracle_with_pubkey(&mut scenario, &clock);

    // First verify — succeeds, uses nonce=1
    ts::next_tx(&mut scenario, HUNTER);
    {
        let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
        let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
        let character = ts::take_shared_by_id<Character>(&scenario, char_id);
        let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);
        verify_build::verify_build(
            &mut bounty, &assembly, &character, &registry,
            BUILD_MSG, BUILD_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
        );
        ts::return_shared(bounty);
        ts::return_shared(assembly);
        ts::return_shared(character);
        ts::return_shared(registry);
    };

    // Second verify — same nonce=1, different timestamp → replay abort
    ts::next_tx(&mut scenario, HUNTER);
    let mut bounty = ts::take_shared<Bounty<SUI>>(&scenario);
    let assembly = ts::take_shared_by_id<Assembly>(&scenario, assembly_id);
    let character = ts::take_shared_by_id<Character>(&scenario, char_id);
    let registry = ts::take_shared<oracle::OracleRegistry>(&scenario);

    verify_build::verify_build(
        &mut bounty, &assembly, &character, &registry,
        BUILD_REPLAY_MSG, BUILD_REPLAY_SIG, ORACLE_ADDR, &clock, ts::ctx(&mut scenario),
    );

    ts::return_shared(bounty);
    ts::return_shared(assembly);
    ts::return_shared(character);
    ts::return_shared(registry);
    clock::destroy_for_testing(clock);
    ts::end(scenario);
}
